### ISSUE TITLE
0.0.3 artifacts use filenames are for 0.0.2

### ISSUE THREAD

**Issue by jadewilk** [KonstantinosPetrakis/open-league-displays#1]
Can't pull that via script because it's not like ``https://github.com/KonstantinosPetrakis/open-league-displays/releases/download/${version}/open-league-displays_${version}_amd64.deb``

**Comment by KonstantinosPetrakis** [comment]
Hello. 

It is resolved. Actually I forgot to increment the version in package.json so build files used the old version.
